name: ecommerce-local
values:
  - key: baseUrl
    value: ''
  - key: testProductId
    value: ''
  - key: tokenA
    value: ''
  - key: tokenB
    value: ''
  - key: tokenAdmin
    value: ''
  - key: tokenAd
    value: ''
  - key: token
    value: ''
